font_family              JetBrainsMono Nerd Font
font_size                12.0
hide_window_decorations  yes

shell zsh -c 'tmux attach 2>/dev/null || tmux new'

background_blur          1
background_image         /home/alienx/Pictures/aaa.jpg
background_image_layout  tiled
background_tint          0.99
background_opacity       0.90
dynamic_background_opacity yes
