[ids]
*

[main]

[alt]
h = left
j = down
k = up
l = right

n = C-z

w = C-right
b = C-left

u = C-a
i = C-c
o = C-v

m = C-s

r = C-backspace
e = C-delete

[alt+shift]
h = S-left
j = S-down
k = S-up
l = S-right

w = C-S-right
b = C-S-left

[alt+control]
h = C-left
j = C-down
k = C-up
l = C-right


[alt+control+shift]
h = C-S-left
j = C-S-down
k = C-S-up
l = C-S-right
[alt+control+shift]
h = C-S-left
l = C-S-right
